from django.conf.urls import url
from . import views

urlpatterns = [

    url(r'^$',views.index,name='index'),
    url(r'^login/$', views.login, name='login'),
    url(r'^signup/',views.signup ,name = 'signup'),
    url(r'^introduction/',views.introduction,name='introduction' ),
    url(r'^team/',views.team ,name='team'),
    url(r'^download/',views.download,name='download'),
    url(r'^user/',views.user,name='user' ),
    url(r'^user.1/',views.user1,name='user.1' ),
    url(r'^contact/',views.contact,name='contact' ),
    url(r'^login/forgot/',views.forgot ),
    url(r'^personal/$', views.personal,name='personal'),
    url(r'^personal/apply/', views.apply,name='apply'),
    url(r'^personal/change/', views.change, name='change'),
    url(r'^administrator/$', views.administrator, name='administrator'),
    url(r'^administrator1/$', views.administrator1, name='administrator1'),
    url(r'^personal/passwordChange/', views.password_change,name='passwordChange'),
    url(r'^personal/upload/', views.upload_file,name='upload'),
    url(r'^personal/new_apply/', views.new_apply,name='new_apply'),
    url(r'^personal/new_apply_delete/', views.new_apply_delete,name='new_apply_delete'),
    url(r'^allow_examine/', views.allow_examine,name='allow_examine'),
    url(r'^cancel_examine/', views.cancel_examine,name='cancel_examine'),
    url(r'^map/', views.map,name='map'),
    url(r'^mapexam/', views.mapexam,name='mapexam'),
    url(r'^mapexam1/', views.mapexam1,name='mapexam1'),
    url(r'^pie/', views.pie,name='pie'),
    url(r'^pie2/', views.pie2,name='pie2'),
    url(r'^pie3/', views.pie3,name='pie3'),
    url(r'^logout/', views.logout),
    url(r'^statistics/', views.statistics),
    url(r'^statistics1/', views.statistics1),
]